### ISSUE TITLE
container_t forbidden from container_runtime_tmpfs_t

### ISSUE THREAD

**Issue by hxtk** [containers/container-selinux#103]
I encountered this issue when trying to run the `envoyproxy/envoy:v1.14.1` docker container. Envoy creates a shared memory file in `/dev/shm/envoy_shared_memory_0`, which gets mapped to a file of the form `/var/lib/docker/containers/[^/]+/mounts/shm/envoy_shared_memory_0` on the host machine using the docker container runtime. This file is labeled as `container_runtime_tmpfs_t`, which appears to be the expected behavior and is consistent with other container runtimes.

However, processes of type `container_t` are not permitted to access files of type `container_runtime_tmpfs_t`.

Adding the following type enforcement policy resolves the issue for me, as does setting the container process to run as `spc_t`, but I was wondering if this was a bug or if there is a particular reason that these operations are normally forbidden?

```
require {
	type container_runtime_tmpfs_t;
	type container_t;
	class dir { add_name remove_name read write };
	class file { create open read write };
}

allow container_t container_runtime_tmpfs_t:dir { add_name remove_name read write };
allow container_t container_runtime_tmpfs_t:file { create open read write };
```

**Comment by rhatdan** [comment]
What Docker or Podman command are you using to launch this container?
This looks like this is a volume being mounted into a container.

**Comment by hxtk** [comment]
It appears that the issue is with my particular container runtime. At time of reporting, I experienced this issue with Docker Community Edition, and I am not exactly certain which version, but I've since updated to Docker version 19.03.12, build 48a66213fe and it seems that the file is now labeled as `container_file_t`. This labeling is consistent with Podman 1.6.4.
