### ISSUE TITLE
SELinux errors when docker path is changed

### ISSUE THREAD

**Issue by LM1LC3N7** [containers/container-selinux#111]
Hello,

I encounter SELinux errors when docker path is changed. 
It result in an impossibility to start containers, like "alpine", because of SELinux.

I already opened an issue on moby github repo, but without answers for now, where I explain how to reproduce the issue:
moby/moby#41654

Can you check or help me to debug this?

Thanks!

**Comment by LM1LC3N7** [comment]
Hello all,

The only solution I found is to remove the following line from `/etc/docker/daemon.json`:

```bash
"selinux-enabled": true
```

Which is not a solution..

**Comment by rhatdan** [comment]
This was fixed by fixing the labels on docker .
