### ISSUE TITLE
bump to 2.160.1 ??

### ISSUE THREAD

**Issue by lsm5** [containers/container-selinux#129]
https://github.com/containers/container-selinux/blob/7ffded0091bc146cc47808fa101246091c66b9d8/container.te#L1

Should this be bumped to match the latest tag?

**Comment by lsm5** [comment]
@rhatdan ^

**Comment by rhatdan** [comment]
Maybe, I did not change this since the container.te file did not change only some additional labels.  Bottom line, is it probably does not matter.

**Comment by lsm5** [comment]
> Maybe, I did not change this since the container.te file did not change only some additional labels. Bottom line, is it probably does not matter.

hmm, so far I've been using that line in container.te to get the latest version for rawhide autobuilds. So, if that does not reflect the latest version, can we bring back the VERSION file and follow semver like we do for other repos?

**Comment by rhatdan** [comment]
Ok I will cut a new release.
