### ISSUE TITLE
SELinux preventing systemd from watching /etc/kubernetes (kubernetes_file_t)

### ISSUE THREAD

**Issue by jlebon** [containers/container-selinux#135]
```
Jun 21 15:26:00 localhost audit[1]: AVC avc:  denied  { watch } for  pid=1 comm="systemd"
path="/etc/kubernetes" dev="vda4" ino=18874496 scontext=system_u:system_r:init_t:s0
tcontext=system_u:object_r:kubernetes_file_t:s0 tclass=dir permissive=0
```

```
[core@cosa-devsh ~]$ rpm -q container-selinux
container-selinux-2.162.2-1.fc34.noarch
```

Similar to https://bugzilla.redhat.com/show_bug.cgi?id=1957840, which was fixed by https://github.com/containers/container-selinux/commit/da2828824807d859cee1ac96e1d39c1abd4397da, but it sounds like we need to broaden things a bit more to allow `watch`.

See also: https://github.com/coreos/fedora-coreos-tracker/issues/861

**Comment by jlebon** [comment]
Let me know if you'd prefer I create a Fedora RHBZ for this instead.

**Comment by rhatdan** [comment]
@wrabcak @vmojzis PTAL

 sesearch -A -s init_t -t kubernetes_file_t
allow domain file_type:blk_file map; [ domain_can_mmap_files ]:True
allow domain file_type:chr_file map; [ domain_can_mmap_files ]:True
allow domain file_type:file map; [ domain_can_mmap_files ]:True
allow domain file_type:lnk_file map; [ domain_can_mmap_files ]:True
allow init_t file_type:blk_file { getattr relabelfrom relabelto };
allow init_t file_type:chr_file { getattr relabelfrom relabelto };
allow init_t file_type:dir { getattr ioctl lock open read relabelfrom relabelto search };
allow init_t file_type:fifo_file { getattr relabelfrom relabelto };
allow init_t file_type:file { getattr relabelfrom relabelto };
allow init_t file_type:filesystem { getattr unmount };
allow init_t file_type:lnk_file { getattr relabelfrom relabelto };
allow init_t file_type:sock_file { getattr relabelfrom relabelto };
allow init_t non_security_file_type:dir create; [ init_create_dirs ]:True
allow init_t non_security_file_type:dir setattr; [ init_create_dirs ]:True
allow init_t non_security_file_type:dir { mounton setattr write }; [ init_create_dirs ]:True
allow init_t non_security_file_type:file mounton; [ init_create_dirs ]:True

If init_t can read all file_type directories, it should be able to watch them as well.

**Comment by zpytela** [comment]
You are right, we considered this approach when the watch permissions were introduced, and decided to start with allowing only the known access.
The request for a type outside selinux-policy makes a change, so we will address it in general now.

**Comment by dustymabe** [comment]
Hey @zpytela - can you link us to the upstream changes in selinux-policy when they land? Thanks!

**Comment by dustymabe** [comment]
opened https://bugzilla.redhat.com/show_bug.cgi?id=1980560 to track this.

**Comment by zpytela** [comment]
https://github.com/fedora-selinux/selinux-policy/pull/799 has been merged, will be a part of the next build later this week.

**Comment by rhatdan** [comment]
Ok I am going to close this issue.
