### ISSUE TITLE
systemd --user throws errors when stopping a podman container of a staff_u user

### ISSUE THREAD

**Issue by laolux** [containers/container-selinux#144]
Controlling a podman container with a `systemd --user` service unit on a `staff_u` selinux user throws avc denials when stopping the container via systemd.

Reproducing the error is simple:
1. log in to user with selinux user `staff_u`
2. run container, for example nginx: `podman run -dt -p 8080:8080 --name nginx_regular docker.io/library/nginx:mainline-alpine`
3. create systemd unit: `podman generate systemd -f --new -n nginx_regular`
4. copy to user directory for systemd service files: `cp container-nginx_regular.service .config/systemd/user/`
5. reload systemd user daemon: `systemctl --user daemon-reload`
6. stop the container using podman: `podman stop nginx_regular`
7. start the container using systemd: `systemctl --user start container-nginx_regular.service`
8. stop the container using sytemd: `systemctl --user stop container-nginx_regular.service`

End result: The container will be stopped, but selinux is not happy about the way this was being done.
The following avc messages are created:

    time->Tue Aug 24 22:32:53 2021
    type=AVC msg=audit(1629858773.605:302): avc:  denied  { signull } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:32:53 2021
    type=AVC msg=audit(1629858773.612:303): avc:  denied  { signull } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:33:09 2021
    type=AVC msg=audit(1629858789.336:308): avc:  denied  { signal } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:33:09 2021
    type=AVC msg=audit(1629858789.336:309): avc:  denied  { sigkill } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:33:09 2021
    type=AVC msg=audit(1629858789.694:310): avc:  denied  { signal } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:33:09 2021
    type=AVC msg=audit(1629858789.694:311): avc:  denied  { sigkill } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0
    ----
    time->Tue Aug 24 22:33:09 2021
    type=AVC msg=audit(1629858789.694:312): avc:  denied  { signull } for  pid=895 comm="systemd" scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process permissive=0

Tested in a freshly setup vm using Fedora 34 server with all updates installed (as of writing).
container-selinux version is `container-selinux-2.164.2-1.fc34.noarch`.
The avc denials do not occur when using an `unconfined_u` user.

**Comment by rhatdan** [comment]
Pushed a fix for this into the main branch.
