### ISSUE TITLE
unable to install k3s-selinux on suse/microos due to conflicting file-context entries

### ISSUE THREAD

**Issue by dweomer** [containers/container-selinux#149]
I am working on enabling k3s on SLES 15sp3, SLE-MicroOS and openSUSE MicroOS systems. In the course of development and testing this I have encountered an issue that prevents the policy to be installed unless I comment out out file-context entries. This seems to be caused by the MicroOS SELinux implementation enforcing a consistency check that we have heretofore not encountered on other systems that we support (el7 and el8 via centos).

The conflicting file-context entries were upstreamed here via #140.

My proposal would be to attempt a claw-back of only the k3s-specific bits from this repo that were included with #140 (i.e. leave the k8s, cni, and flannel entries as-is) and supplement with a conversely modified k3s-selinux policy. As you can see by https://github.com/k3s-io/k3s-selinux/pull/21/files#diff-a91aed3ea17f6544e61fe4e39d429a27316a95d80b7df73c3c43c76c9261a249, I have had to comment out all overlapping file-context entries so as to get the k3s-selinux policy to install.

(see also https://github.com/dweomer/k3s-selinux/blob/v0.5.testing.1/policy/microos/k3s.fc)

@rhatdan should I go ahead and submit that PR? Is there something else that I can try that I am missing?

**Comment by rhatdan** [comment]
Yes those labels should be in container-selinux.

**Comment by dweomer** [comment]
> Yes those labels should be in container-selinux.

By "those labels" I figured that you meant the k8s, cni, flannel file-context entries that were brought over via #140. My proposal, as can be seen by #151, is that these should indeed be retained here and only the k3s binaries and container locations (specific to k3s) should be removed. See k3s-io/k3s-selinux#21

**Comment by dweomer** [comment]
https://github.com/containers/container-selinux/pull/151#issuecomment-920289345
