### ISSUE TITLE
selinux: Don't hardcode transition to level=s0 for conmon

### ISSUE THREAD

**Issue by bauen1** [containers/container-selinux#152]
**BUG REPORT**

/kind bug

**Description**

* Podman forces a transition to SELinux level `s0` preventing any automatic transitions from the policy from taking effect.

* Podman, or rather `go-selinux` also hard codes the naming of categories, it would be better if it used libselinux instead.

**Steps to reproduce the issue:**

1. Load an selinux policy that audits the `(process (transition))` of podman when executing `conmon`

2. Run a container

3. Observe resulting context (and transition) of podman

**Describe the results you received:**

podman manually transitions to `owncontext:s0` when executing conmon.

**Describe the results you expected:**

podman does not manually transition, allowing the policy to control what context conmon runs as.
This means less hard coding of SELinux levels etc.. in podman and means that conman can be run in a seperate context / different level if wanted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unstable,now 3.0.1+dfsg1-3+b2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

/cc @doverride

**Comment by rhatdan** [comment]
@bauen1 Are you still interested in this?

**Comment by bauen1** [comment]
Yes.

I am however still on vacation so it will take 1-4 weeks for me to get to this, as it isn't particularly high on my todo list.

**Comment by rhatdan** [comment]
Any update?

**Comment by 0xC0ncord** [comment]
It looks like if the policy enforces a type transition from podman to conmon, podman's behavior also causes it to maintain the same type as podman.

For example, if I want `podman_t` to transition to `podman_conmon_t` when executing it, podman's default behavior will ask SELinux to make the resulting conmon process `podman_t` even though the intent is only to force the label to be `s0`.

**Comment by rhatdan** [comment]
Sounds like a bug in Podman?

**Comment by 0xC0ncord** [comment]
Indeed. I intend to submit PRs for this after some more testing.

**Comment by bauen1** [comment]
For cross-reference: https://github.com/containers/container-selinux/pull/166

**Comment by bauen1** [comment]
Err, I meant https://github.com/containers/podman/pull/13093
