### ISSUE TITLE
Provide a way for apps to know which types are provided by container-selinux

### ISSUE THREAD

**Issue by fidencio** [containers/container-selinux#160]
`containerd`, in the hope of maintaining backward compatibility with systems that still rely on an older version of the package, sets the `container_kvm_t` label according to whether they can find the type as part of the `/etc/selinux/targeted/contexts/customizable_types` file.

This, per si, is **wrong**, as that file is provided by the `selinux-policy-targeted` package rather than the `container-selinux` one, but the idea to check which types are provided by `container-selinux` is a reasonable one, I must say.

On the containerd side I'm proposing a workaround, to figure out whether the `container_kvm_t` type is provided by inspecting `/usr/share/containers/selinux/contexts`, but that's a **workaround**, at most a **workaround**.  The ideal solution, IMHO, would be to check which are the types provided by the `container-selinux` package in a standardised way and it seems that having a file with such info would be a reasonable way to go.

@rhatdan, please, let me know your thoughts about this and I can follow up with patches / reviews in case there's no disagreement from your side.

**Comment by rhatdan** [comment]
Much simpler then that. The kernel can identify all types.
```
$ echo -n system_u:system_r:container_kvm_t:s0 > /sys/fs/selinux/context 
$ echo -n system_u:system_r:container_bad_t:s0 > /sys/fs/selinux/context 
bash: echo: write error: Invalid argument
```
