### ISSUE TITLE
2.174.0 : fork/exec /usr/bin/conmon: EPERM

### ISSUE THREAD

**Issue by edsantiago** [containers/container-selinux#168]
Looks like container-selinux-2.174.0-1 broke podman:
```console
# podman info
WARN[0000] Conmon at /usr/bin/conmon invalid: fork/exec /usr/bin/conmon: permission denied
WARN[0000] Conmon at /usr/bin/conmon is invalid: fork/exec /usr/bin/conmon: permission denied
Error: please update to v2.0.24 or later: outdated conmon version
# rpm -q conmon container-selinux
conmon-2.0.30-2.fc36.x86_64
container-selinux-2.174.0-1.fc36.noarch
# tail /var/log/audit/audit.log
...
type=AVC msg=audit(1643892688.750:817): avc:  denied  { entrypoint } for  pid=8129 comm="podman" path="/usr/bin/conmon" dev="vda1" ino=187059 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:conmon_exec_t:s0 tclass=file permissive=0
type=AVC msg=audit(1643892688.753:818): avc:  denied  { entrypoint } for  pid=8130 comm="podman" path="/usr/bin/conmon" dev="vda1" ino=187059 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:conmon_exec_t:s0 tclass=file permissive=0
```
This is on Rawhide but I also saw the same on RHEL8.6 yesterday, module 14102, also with this version of container-selinux.

**Comment by rhatdan** [comment]
Fixed in https://github.com/containers/container-selinux/releases/tag/v2.176.0

**Comment by Procsiab** [comment]
Hi, I experience a similar issue on Fedora IoT 35.20220218.0: whenever I try to run a container with port mapping, both with and without root, I experience the following error from podman:
```
Error: fork/exec /usr/bin/conmon: permission denied
```
And the following SELinux alert is logged consequently:
```
type=AVC msg=audit(1645262592.175:3876): avc: denied { entrypoint } for pid=86125 comm="podman" path="/usr/bin/conmon" dev="mmcblk0p3" ino=377157 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=0 trawcon="system_u:object_r:conmon_exec_t:s0" 
```

These are some of the package versions bundled with that particular Fedora IoT version:
- selinux-policy-35.15-1.fc35.noarch
- container-selinux-2.177.0-1.fc35.noarch
- conmon-2.1.0-2.fc35.aarch64

I tried to relabel the system by creating the `.autorelabel` file and rebooting but at that point I could not login anymore with root or another user.

The only way to resolve this was to manually rollback to the previous Fedora IoT version 35.20220210.0, which comes wioth the following package versions:

- selinux-policy 35.13-1.fc35
- container-selinux 2:2.173.1-1.fc35
- conmon 2.1.0-2.fc35

I could also add a custom rule using sealert, however for now I just relied on the rollback feature of rpm-ostree.
If you need further eevidence, I may try in the following days.
