### ISSUE TITLE
How to install the container-selinux package on Ubuntu

### ISSUE THREAD

**Issue by B3ns44d** [containers/container-selinux#183]
I'm not sure on how to install the container-selinux package on Ubuntu. I tried using `apt-get install container-selinux` but I got  "E: Unable to locate package container-selinux." error message, I've done so on RHEL by using `yum install -y container-selinux.`

```
b3ns44d@rhel:~# yum install -y container-selinux
Updating Subscription Management repositories.
Last metadata expiration check: 0:21:04 ago on Thu 21
 Jul 2022 01:27:21 PM UTC.
Package container-selinux-3:2.179.1-1.el9_0.noarch is
 already installed.
Dependencies resolved.
Nothing to do.
Complete!
b3ns44d@rhel:~# 
```

**Comment by rhatdan** [comment]
This is not an upstream issue.
Ubuntu does not support SELinux out of the box and probably no one has shipped container-selinux for Ubuntu.
