### ISSUE TITLE
Set up CI to test various container engines on Fedora (and/or EL)

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/container-selinux#191]
Would it be possible to set up CI to test various container engines with SELinux on Fedora (and/or EL)?

GHA does not provide Fedora instances, but nested virtualization is available on the macOS instances of GHA and the Linux instances of Cirrus.

**Comment by rhatdan** [comment]
I don't really think this would be worth it.  We are not changing this Repo often and are almost always loosening the SELinux policy. The issues with SELinux policy almost always come from the way tools use it.  It would be better if Podman, Docker, containerd, cri-o, buildah, buildkitd tested SELinux in their own environments.
