### ISSUE TITLE
dbus-broker and pipefs

### ISSUE THREAD

**Issue by leseb** [containers/container-selinux#197]
I have an application that talks through D-Bus, the client runs in a container and sends a message, and the server does whatever it needs to do and then replies.
On a particular call, I'm getting:

```
Nov 21 16:22:09 localhost.localdomain audit[704]: AVC avc:  denied  { read } for  pid=704 comm="dbus-broker" path="pipe:[141146]" dev="pipefs" ino=141146 scontext=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 tcontext=unconfined_u:system_r:spc_t:s0 tclass=fifo_file permissive=0
```

After further investigation I get  the following recommendation:

```
$ ausearch -m AVC -ts recent | audit2allow -R

require {
	type system_dbusd_t;
}

#============= system_dbusd_t ==============
container_spc_rw_pipes(system_dbusd_t)
```

I'm thinking of editing `container.te` but I'd need some guidance as to where this should go (assuming my request is correct).

I've managed to add a new policy and it worked based on:

```
$ ausearch -c 'dbus-broker' --raw | audit2allow -M dbus-broker
******************** IMPORTANT ***********************
To make this policy package active, execute:

semodule -i dbus-broker.pp


$ semodule -X 300 -i dbus-broker.pp
```

My file looks like this:

```
$ cat dbus-broker.te

module dbus-broker 1.0;

require {
	type spc_t;
	type system_dbusd_t;
	class fifo_file read;
}

#============= system_dbusd_t ==============
allow system_dbusd_t spc_t:fifo_file read;
```

I've also attached the `dbus-broker.pp` file.

Thanks for considering this issue.

**Comment by rhatdan** [comment]
Does your application actually break, or does this AVC just appear?

**Comment by leseb** [comment]
The command that sends a message to D-Bus fails and the AVC is generated at this point.

**Comment by rhatdan** [comment]
Lets go a back door on this and do.

init_initrc_domain(spc_t)

**Comment by leseb** [comment]
How can I test this?  Thanks for your help.

**Comment by rhatdan** [comment]
Fixed in https://github.com/containers/container-selinux/releases/tag/v2.193.0

I tested that change against the AVC and I believe it will fix the problem

**Comment by leseb** [comment]
Thanks @rhatdan, I built and installed the RPM for 2.193.0, and now everything works!

**Comment by leseb** [comment]
For posterity, this was fixed by https://github.com/containers/container-selinux/commit/88f904d48e7c79265fa01dd270f511492bf4ff66 as mentioned in https://github.com/containers/container-selinux/issues/197#issuecomment-1323766036.
