### ISSUE TITLE
Unable to install on CS9 against selinux-policy 38.1.1-1.el9

### ISSUE THREAD

**Issue by cjeanner** [containers/container-selinux#198]
Hello there,

There's apparently an issue with container-selinux 3:2.191.0-1.el9 on CS9: it can't get properly installed, failing with this error:
```
Failed to resolve allow statement at /var/lib/selinux/targeted/tmp/modules/200/container/cil:1219
```

After a check of that CIL file, it happens to be this line:
```
(allow container_domain init_t (bridge_socket (ioctl read write getattr lock append accept getopt)))
```

Apparently, that bridge_socket was removed from selinux-policy [in this patch](https://github.com/fedora-selinux/selinux-policy/commit/ca313456bbb8f079aa3bb57e94eead1222b9f964)

Downgrading selinux-policy (as well as selinux-policy-targeted) to 34.1.47-1.el9 allows to properly install container-selinux, without any issue.

Care to have a look?

Thank you!

Cheers,

C.

PS: this issue is crashing TripleO CI currently, we'll add a quick workaround in order to downgrade the selinux-policy

**Comment by rhatdan** [comment]
@lsm5 Didn't we fix this some how?

**Comment by rhatdan** [comment]
I think this is bridge_socket being in the selinux-policy container-selinux is built against, versus the one it is being instaled on?

**Comment by cjeanner** [comment]
@rhatdan thanks for jumping that fast! Maybe it's just a temporary (?) glitch with the repositories/mirrors then? A bit like the libselinux bump breaking most of the selinux packages earlier this year.

**Comment by rhatdan** [comment]
@wrabcak Do you remember what caused this problem and how it was solved?

**Comment by lsm5** [comment]
> @lsm5 Didn't we fix this some how?

@rhatdan don't remember.

@cjeanner could you please file a cs9 bz as well? I think every cs9 update would need a bz.

/cc @jnovy

**Comment by psss** [comment]
We've run into the issue as well. It seems that when `container-selinux` is installed before `selinux-policy` is updated to the latest version the scriptlet fails.

So this works with a fresh box with `selinux-policy-38.1.1-1.el9.noarch`:

    dnf update -y
    dnf install -y podman
    podman run -it --rm fedora cat /etc/os-release

But this does not with the old `selinux-policy-34.1.34-1.el9.noarch`:

    dnf install -y podman
    dnf update -y
    podman run -it --rm fedora cat /etc/os-release

Reinstalling `container-selinux` fixes the problem:

    dnf reinstall -y container-selinux
    podman run -it --rm fedora cat /etc/os-release

**Comment by psss** [comment]
How could we prevent similar problems? I'm proposing to enable a simple `tmt` integration test for `podman` here:

 * https://gitlab.com/redhat/centos-stream/rpms/podman/-/merge_requests/205

Would it make sense to add a similar one for `container-selinux` as well?

**Comment by edsantiago** [comment]
Thank you. @lsm5 would it be a good idea to update https://gitlab.com/redhat/centos-stream/rpms/container-selinux/-/blob/c9s/container-selinux.spec#L18 ?

**Comment by thrix** [comment]
yeah pls, definitely should be solved on spec level I believe

**Comment by jnovy** [comment]
@cjeanner Would you mid filing a bugzilla against c9s so that I can do the change?

**Comment by cjeanner** [comment]
@jnovy hmmm what component would that be?

**Comment by cjeanner** [comment]
@jnovy guess that's the right one: https://bugzilla.redhat.com/show_bug.cgi?id=2150283 - lemme know if I did it wrong.

**Comment by zpytela** [comment]
As mentioned previously, a temporary glitch, sorry for that. Please use selinux-policy-38.1.2-1.el9.

Policy was rebased in selinux-policy-38.1.1-1.el9 to the current one in Fedora where unused classes were removed. This makes custom policies using socket_class_set macro which expands at the time of compilation to the current policy sources state fail. The classes are now back.

**Comment by rhatdan** [comment]
The container-selinux policy rpm package needs to require the latests selinux-policy package be installed so this does not happen.

**Comment by fansari** [comment]
This was probably related:

https://bugzilla.redhat.com/show_bug.cgi?id=2151876

**Comment by rhatdan** [comment]
Not something container-selinux upstream project can fix. Downstream has a fix as I understand it.
