### ISSUE TITLE
v2.200.0 doesn't build on f37

### ISSUE THREAD

**Issue by lsm5** [containers/container-selinux#203]
```
Compiling targeted container module
container.te:822:ERROR 'unknown class user_namespace' at token ';' on line 32252:
allow container_domain self:lnk_file setattr;
allow container_domain self:user_namespace create;
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[1]: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/container.mod] Error 1
make[1]: Leaving directory '/home/lsm5/repositories/pkgs/container-selinux/BUILD/container-selinux-2.200.0'
make: *** [Makefile:12: container.pp] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.rSuECH (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.rSuECH (%build)
```

**Comment by rhatdan** [comment]
Yes this seems to be a new access control check on F38.  Not sure the best way to handle this, other then breaking them appart.
This is going to become an issue with RHEL.

Currently I think we just remove that line in F37.

**Comment by lsm5** [comment]
> Yes this seems to be a new access control check on F38. Not sure the best way to handle this, other then breaking them appart. This is going to become an issue with RHEL.
> 
> Currently I think we just remove that line in F37.

I'll remove the user_namespace line from f37 and f36. Thanks

**Comment by vmojzis** [comment]
Yes user_namespace is currently only available in Fedora 38+. Not sure if it will make it's way into RHEL 9.
