### ISSUE TITLE
Branch protection for main branch

### ISSUE THREAD

**Issue by lsm5** [containers/container-selinux#207]
@rhatdan We should enable some rules to protect the main branch.

At the very least:
* Require a pull request before merging
* Do not allow bypassing the above settings

![image](https://user-images.githubusercontent.com/247367/222710034-14dd4f30-9c96-4e23-a874-f542fccda129.png)

One anomaly I notice is that even though https://github.com/containers/container-selinux/pull/204 was merged, it's content isn't visible in the main branch and I don't see any PR done to undo those changes. Which makes me suspect a force push probably wiped it out.

**Comment by lsm5** [comment]
> * Require a pull request before merging
> * Do not allow bypassing the above settings

I've enabled these 2 rules for now.

**Comment by lsm5** [comment]
we should check if more rules can be enabled for better protections.

**Comment by rhatdan** [comment]
This looks good.  I am going to close this issue, since you turned on a couple of protections.
