### ISSUE TITLE
gating tests?

### ISSUE THREAD

**Issue by lsm5** [containers/container-selinux#211]
@rhatdan so far we don't have any gating tests running on every PR apart from the build tests. Do you have any recommendations on what kind of tests to run, preferably both upstream and fedora gating? Something like [selinux-testsuite](https://github.com/SELinuxProject/selinux-testsuite) perhaps?

**Comment by rhatdan** [comment]
I would like to just compile and install the container.pp file.

podman/e2e/run_selinux_test.go
podman/system/410-selinux.bats

Should work.
