### ISSUE TITLE
container_init_t does not possess ptrace process context

### ISSUE THREAD

**Issue by robbmanes** [containers/container-selinux#273]
Copied from [RHEL-10117](https://issues.redhat.com/browse/RHEL-10117).

## What were you trying to do that didn't work?
When running init/systemd containers with podman, the security process label of `container_init_t` does not posses ptrace capabilities, however, `container_t` does.  This prevents commands like `nsenter -Z` from working properly on images where init/systemd is the root process, such as our own ubi-init images.

Regular non-init/systemd containers are assigned `container_t` and have `deny_ptrace` set to `false`:
```
# podman run -d --name sleeper --rm registry.redhat.io/ubi8 sleep infinity

# podman inspect sleeper | jq '.[].State.Pid'
2608

# ps -Z 2608
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:container_t:s0:c102,c306 2608 ? Ss    0:00 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep infinity

# sesearch -A -s container_t -t container_t -c process -p ptrace allow container_t container_t:process ptrace; [ deny_ptrace ]:False
```

However, and I suspect this is an oversight, processes assigned `container_init_t` have no such definition:
```
# podman run -d --name systemd --rm registry.redhat.io/ubi8-init

# podman inspect systemd | jq '.[].State.Pid'
3004

# ps -Z 3004
LABEL                               PID TTY      STAT   TIME COMMAND
system_u:system_r:container_init_t:s0:c83,c754 3004 ? Ss   0:00 /sbin/init

# sesearch -A -s container_init_t -t container_init_t -c process -p ptrace
```
The end result seems to be that executing `nsenter -Z` results in `permission denied` for this process due to it's process label
```
# /bin/nsenter -Z -m -n -p -t 3004 strace ls
nsenter: failed to execute /usr/bin/strace: Permission denied
```
## How reproducible:
Every time.

## Steps to reproduce
- Launch an `init` container that is assigned container_init_t context.
- Attempt to ptrace inside of the container with nsenter, keeping contexts via -Z.
- Observe failure.

## Expected results
Unable to ptrace using -Z with nsenter.

##Actual results
Similar behavior to container_t.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan this has a rather hot Jira Card assigned to it.  If you could PTAL as soon as you can, I'd appreciate it.

**Comment by rhatdan** [comment]
allow container_t container_t:capability { audit_write chown dac_read_search fowner kill mknod net_admin net_bind_service net_raw setfcap setgid setpcap setuid sys_chroot };

allow container_init_t container_init_t:capability { audit_write chown dac_read_search fowner kill mknod net_bind_service net_raw setfcap setgid setpcap setuid sys_chroot };

Neither container_t or container_init_t have CAP_SYS_PTRACE.  You can add this by launching the container with --cap-add CAP_SYS_PTRACE

**Comment by rhatdan** [comment]
```
$ sesearch -A -s container_init_t -c capability -p sys_ptrace
allow container_init_t container_init_t:capability { audit_control dac_override fsetid ipc_lock ipc_owner lease linux_immutable net_admin net_broadcast sys_admin sys_boot sys_nice sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config }; [ virt_sandbox_use_all_caps ]:True
$ sesearch -A -s container_t -c capability -p sys_ptrace
allow container_t container_t:capability { audit_control dac_override fsetid ipc_lock ipc_owner lease linux_immutable net_broadcast sys_admin sys_boot sys_nice sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config }; [ virt_sandbox_use_all_caps ]:True
```
I would guess our system is running without this boolean turned on.

**Comment by rhatdan** [comment]
```
$ sesearch -A -s container_init_t -c capability -p sys_ptrace
allow container_init_t container_init_t:capability { audit_control dac_override fsetid ipc_lock ipc_owner lease linux_immutable net_admin net_broadcast sys_admin sys_boot sys_nice sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config }; [ virt_sandbox_use_all_caps ]:True
```

$ rpm -q container-selinux
container-selinux-2.222.0-1.fc39.noarch

Could you try with `podman exec` rather then nsenter.

BUT I think the real issue might be that you are being blocked by Capabilities, not SElinux.

Could you run the initial container with --cap-add SYS_PTRACE.

**Comment by robbmanes** [comment]
> BUT I think the real issue might be that you are being blocked by Capabilities, not SElinux.
I don't think that could be, unless I am mistaken here about the context in which this is executed - I disabled SELinux and it worked as-is, as per my reproduction steps in https://github.com/containers/container-selinux/issues/273#issuecomment-1753206473 and at the beginning of this issue.

> Could you try with podman exec rather then nsenter.
Appears to be the same result if I do `podman exec`, and continues to work if I pet SELinux in permissive:
```
# getenforce
Enforcing

# podman run -d --name systemd --rm registry.redhat.io/ubi8-init

# podman exec -it systemd yum install strace -y

# podman exec -it systemd strace ls
strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Permission denied
strace: ptrace(PTRACE_TRACEME, ...): Permission denied
+++ exited with 1 +++

# setenforce 0

# podman exec -it systemd strace ls
execve("/usr/bin/ls", ["ls"], 0x7ffe948ff310 /* 4 vars */) = 0
[...]
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

> Could you run the initial container with --cap-add SYS_PTRACE.

The `ptrace` syscall continues to be denied.
```
# podman run -d --name systemd --cap-add=SYS_PTRACE --rm registry.redhat.io/ubi8-init

# podman exec -it systemd yum install strace -y

# podman exec -it systemd strace ls
strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Permission denied
strace: ptrace(PTRACE_TRACEME, ...): Permission denied
+++ exited with 1 ++

# getenforce
Enforcing

# setenforce 0

# getenforce
Permissive

# podman exec -it systemd strace ls
execve("/usr/bin/ls", ["ls"], 0x7ffe5cf03690 /* 4 vars */) = 0
[...]
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
I believe that places this as something particular to SELinux, which I believe to be, at least to my understanding, a difference in `container_init_t` process contexts, no?  I am not very versed on SELinux as it applies to processes.

Can you reproduce this with the steps I've provided?  My end customer can as well on RHEL, I did Fedora and the upstream packages just for completeness.  Thanks.

**Comment by rhatdan** [comment]
Please attach the AVC messages.

**Comment by slcmpunk** [comment]
I can reproduce this as well on my RHEL9.2 system:

```
	[root@rhel9 ~]# rpm -q container-selinux
	container-selinux-2.205.0-1.el9_2.noarch
	[root@rhel9 ~]# rpm -q podman
	podman-4.4.1-12.el9_2.x86_64

	[root@rhel9 ~]#  podman run -d --name systemd --rm registry.redhat.io/ubi8-init
	Trying to pull registry.redhat.io/ubi8-init:latest...
	Getting image source signatures
	Checking if image destination supports signatures
	Copying blob d0c0191a2d40 done  
	Copying blob f992cb38fce6 done  
	Copying config b5452e5e96 done  
	Writing manifest to image destination
	Storing signatures
	f46e3a9dbf8c14496a5461ea3523278243175603b031b3727db3fc4883b86cc5

	[root@rhel9 ~]# podman inspect systemd | jq '.[].State.Pid'
	3342481
	[root@rhel9 ~]# ps -Z 3342481
	LABEL                               PID TTY      STAT   TIME COMMAND
	system_u:system_r:container_init_t:s0:c570,c783 3342481 ? Ss   0:00 /sbin/init
	[root@rhel9 ~]# podman exec -it systemd yum install strace -y --quiet
		                                                 
	Installed: strace-5.18-2.el8.x86_64                                                                                                                                                                                                                            

	[root@rhel9 ~]# /bin/nsenter -Z -m -n -p -t 3342481 strace ls
	strace: test_ptrace_get_syscall_info: PTRACE_TRACEME: Permission denied
	strace: ptrace(PTRACE_TRACEME, ...): Permission denied
	+++ exited with 1 +++
	[root@rhel9 ~]# setenforce 0
	[root@rhel9 ~]# /bin/nsenter -Z -m -n -p -t 3342481 strace ls
	execve("/usr/bin/ls", ["ls"], 0x7ffdcfbdb7c0 /* 30 vars */) = 0
	brk(NULL)                               = 0x55a30ea32000
	~
	~
	~
	close(1)                                = 0
	close(2)                                = 0
	exit_group(0)                           = ?
	+++ exited with 0 +++
```

**Comment by rhatdan** [comment]
I got it.

**Comment by rhatdan** [comment]
Fixed in https://github.com/containers/container-selinux/pull/279

**Comment by robbmanes** [comment]
Excellent, thank you @rhatdan; I built a new `container-selinux` package with commit https://github.com/containers/container-selinux/pull/279/commits/4b384f0a49d1d09e7e42090e7e450acad47c434c in it and can confirm it solves the problem.  Much appreciated.
