### ISSUE TITLE
/etc/kubernetes filetrans?

### ISSUE THREAD

**Issue by maage** [containers/container-selinux#283]
Should
https://github.com/containers/container-selinux/blob/31e9f0bdcc6bd5e2a8f7fe651953f3e9f7c56c5d/container.if#L576
Be
files_etc_filetrans
as it tries to manage this
https://github.com/containers/container-selinux/blob/31e9f0bdcc6bd5e2a8f7fe651953f3e9f7c56c5d/container.fc#L164
and there is no //var/run/kubernetes fcontext set.

**Comment by rhatdan** [comment]
Makes sense to me.
