### ISSUE TITLE
Merge container-selinux policy into TresysTechnology/refpolicy-contrib

### ISSUE THREAD

**Issue by rustogi** [containers/container-selinux#44]
Is there a plan to merge container-selinux policy into TresysTechnology/refpolicy-contrib at some point?

**Comment by rhatdan** [comment]
I have no problem merging it or if you want to open a PR that is fine with me.

**Comment by rustogi** [comment]
If you don't mind doing it, then I would prefer that.

**Comment by rhatdan** [comment]
@wrabcak How hard would this be to do?  And does it even make sense?

**Comment by rhatdan** [comment]
This is not going to happen.
