### ISSUE TITLE
Transition blocked when using docker "no-new-privileges"

### ISSUE THREAD

**Issue by brthor** [containers/container-selinux#51]
Container-SELinux  2.36 doesn't seem to play nicely with `no-new-privileges` on CentOS7.

I've been unable to update the container-linux version to 2.48 due to the dependency chain packages not being available on the centOS repos. Trying to build the repo itself with `make install` ends with a syntax error. Seems likely this is because the underlying selinux-policy version is not matching.

It's possible this is fixed in future versions, but I haven't yet been able to test it out. 

[It looks like this happened before.](https://www.projectatomic.io/blog/2016/03/no-new-privs-docker/)

> Turning on no_new_privs actually stopped the SELinux transition from the docker daemon type docker_t to the container type, svirt_lxc_net_t. The no_new_privs option only allows SELinux transitions from one type to another if the target type as a complete subset of the source type.

# Repro Steps

1. Create CentOS VM, I am using latest released AMI on EC2 (ami-4bf3d731)

2. [Install Docker-CE](https://docs.docker.com/install/linux/docker-ce/centos/), and enable edge repo
Checking versions:
```
$ rpm -q container-selinux
container-selinux-2.36-1.gitff95335.el7.noarch
$ rpm -q docker-ce
docker-ce-18.02.0.ce-1.el7.centos.x86_64
```

3. Enable docker SELinux, `sudo vi /etc/docker/daemon.json` and add the following content:
```
{
	"selinux-enabled": true
}
```

4. Don't forget to restart dockerd `sudo systemctl restart docker`

5. Try to run a container with `--security-opt=no-new-privileges`
```
$ sudo docker run --security-opt=no-new-privileges -it alpine sh
standard_init_linux.go:195: exec user process caused "operation not permitted"
```

6. Check out the audit log
```
$ sudo tail -n 500 /var/log/audit/audit.log

...
type=SELINUX_ERR msg=audit(1519087517.808:2497): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:container_runtime_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c433,c559
...
```

# Workaround

The only workaround seems to be to manually add a typebound for the blocked transition classes.

See: https://stackoverflow.com/questions/44127247/does-anyone-know-a-workaround-for-no-new-privileges-blocking-selinux-transitions

```
module dockersvirt 1.0;

require {
    type container_runtime_t;
    type svirt_lxc_net_t;
    role system_r;
};

typebounds container_runtime_t svirt_lxc_net_t;
```

I don't have a proper understanding of SELinux or the entirety of the policies to know if this is a proper workaround, but it seems potentially unsafe at a glance.

If this issue is in the wrong place, please point me in the right direction. If there is another known workaround, please let me know.

**Comment by brthor** [comment]
ping @rhatdan

**Comment by rhatdan** [comment]
I just updated container-selinux in brew with a fix for this removing typebounds but adding nnp_transition and nosuid_transition.  This can not be used until RHEL7.5 is released.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/container-selinux/tree/RHEL7.5

**Comment by brthor** [comment]
Hey thanks for the quick response.

I'll take another look at this after rhel 7.5 is released. Looking forward to user namespace support as well hopefully.

**Comment by rhatdan** [comment]
I think this is fixed in the current release.
