### ISSUE TITLE
Request: add user docs

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/container-selinux#58]
@rhatdan 

Could you add docs that would be useful for end users, including tips such as chconning files to `container_file_t` or `container_share_t`?

**Comment by rhatdan** [comment]
Sure we could add references to some of the blogs that I have written on using containers-storage.

https://www.livejournal.com/rsearch?q=container_file_t&journal=danwalsh&searchArea=post

https://www.projectatomic.io/docs/docker-and-selinux/
https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
https://www.projectatomic.io/blog/2016/07/docker-selinux-flag/
https://www.projectatomic.io/blog/2017/02/selinux-policy-containers/
https://www.projectatomic.io/blog/2016/03/dwalsh_selinux_containers/
https://www.projectatomic.io/blog/2016/03/selinux-and-docker-part-2/
https://www.projectatomic.io/blog/2016/03/no-new-privs-docker/

**Comment by rhatdan** [comment]
@ashley-cui Could you open a PR to fix the README.md to reference these blogs.

**Comment by rhatdan** [comment]
Fixed by https://github.com/containers/container-selinux/pull/74
