### ISSUE TITLE
Loading docker volume fails after upgrade Fedora Ugrade container-selinux.noarch 2:2.77-1.git2c57a17.fc29 

### ISSUE THREAD

**Issue by omerule** [containers/container-selinux#60]
Goodafternoon, after upgrading to "container-selinux.noarch 2:2.77-1.git2c57a17.fc29"
I try to start my docker image.
But I get the error:
/usr/bin/docker-current: Error response from daemon: SELinux relabeling of /var/lib/docker/volumes/openhab_userdata/_data is not allowed: "no such file or directory".
But the directory /var/lib/docker/volumes/openhab_userdata/_data"  is there.

Could this be related to the update?

Yours kindly,
Roel

**Comment by rhatdan** [comment]
Are you seeing AVC messages?

`ausearch -m avc -ts recent`

You could try to relabel the directories.

`restorecon -R -v /var/lib/docker`

**Comment by omerule** [comment]
Thanks for the reply, I did
"sudo ausearch -m avc -ts recent"  the result is "<no matches>".
Also did "sudo restorecon -R -v /var/lib/docker" but then I got the message:
on the directory: 
"/var/lib/docker/volumes/openhab_userdata/_data/ not reset as customized by admin to system_u:object_r:container_file_t:s0"  

Yours kindly
Roel

**Comment by rhatdan** [comment]
That looks fine.

**Comment by rhatdan** [comment]
Can you do the ausearch command right after the docker command fails.

**Comment by omerule** [comment]
The result of "sudo restorecon -R -v /var/lib/docker" idem: 
"sudo ausearch -m avc -ts recent" the result is "<no matches>".

**Comment by rhatdan** [comment]
Does the issue go away when you do a setenforce 0?  If not then this is not an SELinux issue. and the update is probably a `red herring`.

**Comment by omerule** [comment]
Probably a red herring,
With $ sudo setenforce 0 the message within docker is the same.
I thought the update and the error where related.

For now the solution is to create a new volume no problem.
Thank you for the work and reply s.
And a good 2019!

Yours kindly
Roel
The Netherlands

**Comment by omerule** [comment]
There was a problem with the Raspberry Pi 3B+ and de XFS filesystem.
After xfs_repair -L and a reboot a was able to remove the directory with the error message.
