### ISSUE TITLE
What's the best practice to upgarde selinux? 

### ISSUE THREAD

**Issue by haoqing0110** [containers/container-selinux#67]
Enable selinux, and upgrade container-selinux from 2.9 to 2.68, meet below error in docker:
```
# docker run --rm -v /opt/kubernetes/:/data:z myimage:latest sh -c 'cp -f /hyperkube /data/'
sh: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
From https://github.com/containers/container-selinux/blob/master/contrib/container-selinux.spec#L104, seems`restorecon -R -v /var/lib/docker` is skipped in upgrade. After I manually run `restorecon -R -v /var/lib/docker`, above issue resolved. 

And refer to https://github.com/containers/container-selinux/issues/60#issuecomment-450495226 Is that mean, I have to manually run `restorecon -R -v /var/lib/docker` each time after upgarde selinux? 

Why `restorecon -R -v /var/lib/docker` is skipped , and what's the best practice to upgarde selinux?

**Comment by rhatdan** [comment]
@haoqing0110 It should never be needed again.  It is supposed to be done the first time it installs.  Somehow this got mislabeled.
BTW Have you tried podman?

**Comment by haoqing0110** [comment]
@rhatdan so if I meet above issue, it that ok to `restorecon` to whole dir  `/var/lib/docker`? It takes quite a few minutes to finish running. 

Do you have any suggestion how to debug which file is mislabeled?

**Comment by rhatdan** [comment]
It is ok to restoreon on it. Although most likely not neessary.  Usually the AVC will mention a file name (Sadly not a path).  If you know where this file is, you could try a restorecon on it.  But I would doubt that is the issue.
Usually one you fix fix the labeling on /var/lib/docker or /var/lib/containers for podman you are good to go.

Most people experience SELinux issues when volume mounting in content into a container.  And the :z and :Z options help out  in that case.

I wrote these articles to explain SELinux and containers

https://opensource.com/article/18/2/understanding-selinux-labels-container-runtimes
https://www.projectatomic.io/docs/docker-and-selinux/
