### ISSUE TITLE
Allow container to access ns_last_pid

### ISSUE THREAD

**Issue by adrianreber** [containers/container-selinux#71]
The newest selinux-policy package for F29 F30 and rawhide labels `/proc/sys/kernel/ns_last_pid` with `sysctl_kernel_ns_last_pid_t`.

A test build of container-selinux with `kernel_rw_kernel_ns_lastpid_sysctl(container_domain)` enabled CRIU to restore a container with threads.

Can `kernel_rw_kernel_ns_lastpid_sysctl(container_domain)` be added to container-selinux?

Needed for https://github.com/containers/libpod/pull/2705 and https://github.com/containers/libpod/pull/2272

**Comment by rhatdan** [comment]
It is already in 

```
rpm -q container-selinux
container-selinux-2.100-1.git3b78187.fc30.noarch

sesearch -A -s container_t -t sysctl_kernel_ns_last_pid_t
allow container_domain sysctl_kernel_ns_last_pid_t:dir { getattr ioctl lock open read search };
allow container_domain sysctl_kernel_ns_last_pid_t:file { append getattr ioctl lock open read write };
allow container_domain sysctl_type:dir { getattr ioctl lock open read search };
allow container_domain sysctl_type:file { getattr ioctl lock open read };
allow svirt_sandbox_domain sysctl_type:dir { getattr ioctl lock open read search };
allow svirt_sandbox_domain sysctl_type:file { getattr ioctl lock open read };
```
Went i in container-selinux 2.96.
```
* Thu Apr 04 2019 Dan Walsh <dwalsh@fedoraproject.org> - 2.96-1
- Allow containers to read/write sysctl_kernel_ns_last_pid_t
```

**Comment by adrianreber** [comment]
Thanks. Should have looked closer. I was finally able to enable checkpoint/restore in Podman's CI again and all tests are green: https://github.com/containers/libpod/pull/2705
