### ISSUE TITLE
accessing /etc/pki/ca-trust/extracted/pem files from a container

### ISSUE THREAD

**Issue by cpasquini** [containers/container-selinux#77]
I am running Kubernetes in RHEL 7.7 using container-selinux.noarch           2:2.107-3.el7

When mounting the /etc/pki/ca-trust/extracted/pem directory (read only) I am unable to read the contents of any of the files.  Running an audit2allow produced the following policy suggestion:

#============= container_t ==============
allow container_t cert_t:dir read;

can that be added to the main container-selinux release, or is there a better way to handle this?

**Comment by rhatdan** [comment]
The question would be whether or not we should allow this by default.  If a container broke out and was able to read this content, it could then use it to attack other sites, Correct, and their could be some secret data stored there.

This is the perfect use case for UDICA.
https://github.com/containers/udica
@wrabcak WDYT?

**Comment by wrabcak** [comment]
Yes, exactly this is good use case for udica. 
Unfortunately, Udica is not supported in RHEL-7 but we have build in copr:
https://copr.fedorainfracloud.org/coprs/lvrabec/udica/repo/epel-7/lvrabec-udica-epel-7.repo
