### ISSUE TITLE
Question about container_runtime_domain

### ISSUE THREAD

**Issue by a-palchikov** [containers/container-selinux#78]
I was wondering whether it was considered to make `container_runtime_t` into an attribute `container_runtime_domain` so that 3rd party container engines that need custom rules can still inherit the base `container_runtime_t` configuration?

**Comment by rhatdan** [comment]
Sure, I have no problem doing that.
Would you like to open a PR?

**Comment by rhatdan** [comment]
BTW What container engine are you interested in?

**Comment by a-palchikov** [comment]
@rhatdan It's a [custom engine](https://github.com/gravitational/planet/) built directly with `libcontainer`. I've been working on SELinux support and, being a total noob, have to consider all options. The problem with our use-case is that systemd runs quite a few services (instead of simpler case of a single service) so a way to confine all of them is still unclear to me.

I've first looked into labeling the rootfs entirely with the host rules but ran into major issues that would amount to a lot of SELinux configuration to make this work. Additionally, I've never found a way to do away with the ambiguity of having two `etc_t`, `var_t`, etc. without giving the binary only the permissions to manage the content inside of rootfs (and now the host's `etc_t`).

So, my next idea is to tailor as much as possible from this project, hence I wondered if it was possible to re-use the policy without too much duplication while still being open for changes.

**Comment by rhatdan** [comment]
I just pushed a new version of container-selinux.  Which includes the container_runtime_domain attribute.
You can create a type with the interface
container_runtime_domain_template(mycontainer_runtime)

This will create a myconfiner_runtime_t type that should allow you to launch containers and extend the type.

**Comment by rhatdan** [comment]
@wrabcak FYI

**Comment by a-palchikov** [comment]
@rhatdan Thanks a lot!

**Comment by wrabcak** [comment]
Great idea @a-palchikov @rhatdan, AFAIK there is no need to do anything in selinux-policy.

Thank you for heads up!
Lukas
