### ISSUE TITLE
Disable --security-opt and --privileged

### ISSUE THREAD

**Issue by monken** [containers/container-selinux#79]
I've successfully configured SELinux for docker and it's working as expected. My primary goal is to allow an unprivileged (except for being member of the `docker` group) developer to use Docker on a virtual machine. I want to prevent, that the user gains root access to the host file system by mounting the root filesystem in a container. SELinux seems to get me there half-way, as the default will label the container correctly and access to the root filesystem is denied:

```
$ docker run -ti --rm -v /:/host ubuntu:18.04 touch /host/foo
touch: cannot touch '/host/foo': Permission denied
```

However, the user is free to pass `--security-opt label:disable` and will effectively disable all SELinux policies for the given container:

```
$ docker run -ti --rm -v /:/host --security-opt label:disable ubuntu:18.04 touch /host/foo
# succeeds
```

Is there a way to enforce labeling and preventing the user to launch a container in privileged mode?

**Comment by rhatdan** [comment]
Have you looked at Rootless Podman. That really gets you what you want, by not allowing the user to have access to root at all.

**Comment by monken** [comment]
@rhatdan thanks for pointing me in that direction. That looks very promising.
