### ISSUE TITLE
Unable to copy files using Python across certain contexts

### ISSUE THREAD

**Issue by leiflm** [containers/container-selinux#81]
**Problem**: Python raises a permission denied error and aborts due EACESS while trying to legitimately relabel files within a container.

**Environment**:
- Host System: Fedora 31 with enforced SELinux
- Container Daemon: podman (unprivileged)
- image: `fedora:latest`
- `ext4` loop volume handed in as `/relabel_bug`

podman setup:
```sh
podman run -v '/home/test/relabel_bug:/relabel_bug:Z' -it fedora:latest /bin/bash
```

mounted volumes:
```
# mount
fuse-overlayfs on / type fuse.fuse-overlayfs (rw,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c552,c859",size=65536k,mode=755,uid=1000,gid=1000)
/home/test/relabel_bug_container on /relabel_bug type ext4 (rw,relatime,seclabel)
tmpfs on /run/secrets type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=798884k,mode=700,uid=1000,gid=1000)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",gid=100004,mode=620,ptmxmode=666)
tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=798884k,mode=700,uid=1000,gid=1000)
tmpfs on /etc/hosts type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=798884k,mode=700,uid=1000,gid=1000)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",size=64000k,uid=1000,gid=1000)
tmpfs on /etc/hostname type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=798884k,mode=700,uid=1000,gid=1000)
tmpfs on /run/.containerenv type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=798884k,mode=700,uid=1000,gid=1000)
cgroup2 on /sys/fs/cgroup type cgroup2 (ro,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)
devtmpfs on /dev/null type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /dev/zero type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /dev/full type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /dev/tty type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /dev/random type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /dev/urandom type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
tmpfs on /proc/acpi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",size=0k,uid=1000,gid=1000)
devtmpfs on /proc/kcore type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /proc/keys type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /proc/latency_stats type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /proc/timer_list type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
devtmpfs on /proc/sched_debug type devtmpfs (rw,nosuid,seclabel,size=3974416k,nr_inodes=993604,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",size=0k,uid=1000,gid=1000)
tmpfs on /sys/firmware type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",size=0k,uid=1000,gid=1000)
tmpfs on /sys/fs/selinux type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",size=0k,uid=1000,gid=1000)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c552,c859",gid=100004,mode=620,ptmxmode=666)
```

permissions on the target directory:
```
# ls -lZd /relabel_bug
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c552,c859 1024 Nov 15 11:00 /relabel_bug
```

create file on a different device:
```
# touch /tmp/some_file
```

use `shutil.copy2` (invoked by many shutil functions) to copy the file
```
# python3
Python 3.7.4 (default, Aug 12 2019, 14:45:07) 
[GCC 9.1.1 20190605 (Red Hat 9.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.copy2('/tmp/some_file', '/relabel_bug/failure')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/shutil.py", line 267, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 209, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib64/python3.7/shutil.py", line 165, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/relabel_bug/failure'
```

```
# ls -lZ /relabel_bug/
total 3
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c552,c859 0 Nov 15 11:00 failure
```

SE Alert
```
type=AVC msg=audit(1573815617.682:1332): avc:  denied  { relabelto } for  pid=3157530 comm="python3" name="failure" dev="loop1" ino=12 scontext=system_u:system_r:container_t:s0:c552,c859 tcontext=system_u:object_r:fusefs_t:s0 tclass=file permissive=0


Hash: python3,container_t,fusefs_t,file,relabelto
```

Update 1: Corrected the described python invocation (~~`copy`~~ -> `copy2` )

**Comment by doverride** [comment]
If i understand correctly from op, then this does not happen with `cp -a`. I wonder whether that is because coreutils is built with libselinux whereas python is not built with selinux awareness.

**Comment by leiflm** [comment]
> If i understand correctly from op, then this does not happen with `cp -a`.

correct.

**Comment by rhatdan** [comment]
In this container could you run `id -Z`, to see if the container thinks SELinux is disabled. It looks like Python3 is attempting to do an SELinux action, but it is not supposed to think SELinux is enabled within the container.

**Comment by leiflm** [comment]
> In this container could you run `id -Z`, to see if the container thinks SELinux is disabled.

```
# id -Z
id: --context (-Z) works only on an SELinux-enabled kernel
```

> It looks like Python3 is attempting to do an SELinux action, but it is not supposed to think SELinux is enabled within the container.

As mentioned above, this is stock `fedora:latest` container. Should I be running something different?

**Comment by leiflm** [comment]
> > In this container could you run `id -Z`, to see if the container thinks SELinux is disabled.
> 
> ```
> # id -Z
> id: --context (-Z) works only on an SELinux-enabled kernel
> ```

Regarding the reliableness of `id -Z`, I'd like to cite @rhatdan from [another bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1663068#c7) here:
> Sorry id -Z might be lying to you.
> Inside the container do:
> cat /proc/self/current/attr

There is a small swapping mistake in the path argument there, yet here we go.

Inside the container:
```
# cat /proc/self/attr/current 
system_u:system_r:container_t:s0:c189,c689
```

Outside the container:
```sh
$ getenforce 
Enforcing
```

Yet I'm not really sure what to do with this information. Is Python looking at the wrong info here?

**Comment by rhatdan** [comment]
This is what I am thinking.  Could you open a bugzilla on Python and add me as a CC.  Then we can discuss it with the packagers.

**Comment by leiflm** [comment]
Thanks for your help here.

> Could you open a bugzilla on Python and add me as a CC. Then we can discuss it with the packagers.

https://bugs.python.org/issue38893

I hope the description is correct. If not, feel free to add information or let me know what to change about it.

**Comment by adelton** [comment]
@rhatdan, Is it expected / correct that with rootless podman containers and FUSE, the content of the image inside of the container is labelled with `fusefs_t`, instead of `container_file_t`? If the labels were `container_file_t`, python would likely not try to set the attributes and thus would not do the relabelling.

**Comment by rhatdan** [comment]
@giuseppe Could you try to use fuse-overlayfs with a context mount?
context="system_u:system_r:container_file_t:s0:c1,c2" 

If this worked we could solve the issue.

**Comment by adelton** [comment]
@rhatdan How can that be done for the `/` filesystem? I tried to change this rootless container
```
$ podman run --rm -v /data registry.fedoraproject.org/fedora:31 ls -laZ /data
total 8
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0 4096 Feb 28 14:23 .
drwxr-xr-x. 3 root root system_u:object_r:fusefs_t:s0         4096 Feb 28 14:23 ..
```
to have `container_file_t` on the parent (`/`) directory but `--security-opt=label=filetype:container_file_t` did not seem to help:
```
$ podman run --security-opt=label=filetype:container_file_t --rm -v /data registry.fedoraproject.org/fedora:31 ls -laZ /data
total 8
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0 4096 Feb 28 14:25 .
drwxr-xr-x. 3 root root system_u:object_r:fusefs_t:s0         4096 Feb 28 14:25 ..
```

**Comment by rhatdan** [comment]
Rootless containers use a fuse-overlay system for the host image, which basically is labeled fusefs_t.  Their is no way currently to do what you want.  
@giuseppe Does fuse-overlay support a context mount?  I am not sure if fuse file systems do this at all.
@adelton The --security-opt is only for process labels, we don't allow users to specify mount_labels directly.

**Comment by giuseppe** [comment]
>  @giuseppe Does fuse-overlay support a context mount? I am not sure if fuse file systems do this at all.

AFAICS, the `context=` option has no effect with FUSE

**Comment by rhatdan** [comment]
@stephensmalley WDYT

**Comment by stephensmalley** [comment]
I'm not sure I follow.  The context= mount option is handled by SELinux not by the individual filesystems (the security-related options get extracted from the mount option list by the kernel and fed to the security modules to consume, then the rest go to the filesystem).  The context= mount option should work with FUSE just as it does for other filesystems that do not truly support file security labeling, e.g. vfat or nfs < 4.2.

**Comment by rhatdan** [comment]
That means in rootless containers we should be mounting the fuse-overlay fs with context_mount of the container.

**Comment by rhatdan** [comment]
This issue has nothing to do with container-selinux and can not be fixed in this repo.  Now that the kernel supports rootless overly mounts, this problem may not exist any longer.
