### ISSUE TITLE
unable to install container-selinux-2.74-1.el7

### ISSUE THREAD

**Issue by pruthvigh** [containers/container-selinux#86]
I am trying to install docker-ce on  CentOS 7.4.1708 but, I get a dependency error with container-selinux. 

I got container-selinux-2.9-4.el7 installed but, it needs container-selinux-2.74-1.el7.

I was unable to find the repo for that version. I tried http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.74.el7.noarch.rpm 

But, I am getting a "Cannot open: Skipping." error. How do I turnaround this and install docker-ce?

**Comment by rhatdan** [comment]
You should be able to use any newer version of container-selinux for this system.

Support would be much better on a more recent centos version like 7.5 or later.

container-selinux-2.119.1-1.c57a6f9.el7
This is the latest version for RHEL7
