### ISSUE TITLE
File context of /home/<USER>/.local/share/containers

### ISSUE THREAD

**Issue by tt-why** [containers/container-selinux#91]
Hello world !

I'm wondering if it is a good thing to relabel the /home/__USER__/.local/share/containers directory to make that directory have more specific file context. Because by default it has the **data_home_t** context so I imagine many user process context can access it
A quite large list actually : **sesearch -A -t data_home_t -p write**

I could also do another dedicated user, it might be simpler to configure... But i would only rely on DAC permissions.

Here is the command i use :
```
semanage fcontext --add -e /var/lib/containers /home/<USER>/.local/share/containers && \
restorecon -RF /home/<USER>/.local/share/containers
```

## My current setup:
```
dnf list installed | grep -E 'selinux-policy|container-selinux|podman'
container-selinux.noarch                    2:2.124.0-3.fc31                   @updates               
podman.x86_64                               2:1.8.2-2.fc31                     @updates               
podman-plugins.x86_64                       2:1.8.2-2.fc31                     @updates               
selinux-policy.noarch                       3.14.4-49.fc31                     @updates               
selinux-policy-devel.noarch                 3.14.4-49.fc31                     @updates               
selinux-policy-targeted.noarch              3.14.4-49.fc31                     @updates
```

Regards :)

**Comment by rhatdan** [comment]
We could label this as something different perhaps container_home_t or something, but we are really not tring to protect this content from hostile processes in the user session.  Most of this content is readable from the network, so being able to read it, should not be a big deal.

Any content written by the containers will be labeled container_file_t, and would be protected.

Is there content that you believe is risky?

**Comment by tt-why** [comment]
Yeah you're right, I was not thinking about a simple **podman cp** that would bypass type enforcement separation, because podman would still be allowed to access created files of the containerized app.
