### ISSUE TITLE
staff_u rootless podman

### ISSUE THREAD

**Issue by tt-why** [containers/container-selinux#92]
Hello again, i'm stuck at trying to run rootless podman as staff_u...

## First here is my conf :
```
uname -a
Linux desktop 5.5.11-200.fc31.x86_64 #1 SMP Mon Mar 23 17:32:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

dnf list installed | grep -E 'selinux-policy|container-selinux|podman'
container-selinux.noarch                    2:2.124.0-3.fc31                   @updates               
podman.x86_64                               2:1.8.2-2.fc31                     @updates               
podman-plugins.x86_64                       2:1.8.2-2.fc31                     @updates               
selinux-policy.noarch                       3.14.4-49.fc31                     @updates               
selinux-policy-devel.noarch                 3.14.4-49.fc31                     @updates               
selinux-policy-targeted.noarch              3.14.4-49.fc31                     @updates               

getenforce 
Enforcing

podman version
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

## My first issue
I first tried to do a simple **podman version** as a non root user confined as staff_u SELinux user.
But no luck here, the command stays stuck. I'm directly thinking that i might be a SELinux problem so to validate it it did:
**setenforce 0 && podman version && setenforce 1**, and it worked.

I know i'm running as a confined user so i tried :
** semanage permissive -a staff_t && podman version && semanage permissive -d staff_t **, again it worked.

Great, so it might be a problem of the staff.te of the fedora-selinux/selinux-policy github project...

I enabled "debug" mode with semodule -DB and found these avc :
```
----
type=AVC msg=audit(03/29/2020 21:04:53.601:1049) : avc:  denied  { noatsecure } for  pid=202831 comm=bash scontext=staff_u:staff_r:staff_t:s0 tcontext=staff_u:staff_r:container_runtime_t:s0 tclass=process permissive=0 
----
type=AVC msg=audit(03/29/2020 21:04:53.601:1050) : avc:  denied  { rlimitinh } for  pid=202831 comm=podman scontext=staff_u:staff_r:staff_t:s0 tcontext=staff_u:staff_r:container_runtime_t:s0 tclass=process permissive=0 
----
type=AVC msg=audit(03/29/2020 21:04:53.601:1051) : avc:  denied  { siginh } for  pid=202831 comm=podman scontext=staff_u:staff_r:staff_t:s0 tcontext=staff_u:staff_r:container_runtime_t:s0 tclass=process permissive=0 
----
type=AVC msg=audit(03/29/2020 21:04:53.649:1052) : avc:  denied  { sys_ptrace } for  pid=1192 comm=systemd capability=sys_ptrace  scontext=staff_u:staff_r:staff_t:s0 tcontext=staff_u:staff_r:staff_t:s0 tclass=cap_userns permissive=0
```

So i tried to make a quick patch to allow the forbidden rules with that :
```
cat mypodman.te 
policy_module(mypodman, 1.0)
require {
	type container_runtime_t;
	type staff_t;
	class process { noatsecure rlimitinh siginh };
	class cap_userns sys_ptrace;
}
#============= staff_t ==============
allow staff_t container_runtime_t:process { noatsecure rlimitinh siginh };
allow staff_t self:cap_userns sys_ptrace;
```

** semodule -i mypodman.pp && podman version ** : it works, awesome !

## Next issue with a **podman container ls**
Again the command **podman container ls** is stuck :(
** semanage permissive -a staff_t && podman container ls  && semanage permissive -d staff_t ** : it works again...
But this time nothing related with ausearch -i -m avc -m user_avc

## Last issue with a **podman run -it fedora:31 bash**
The following error occurs :
{"msg":"exec container process `/usr/bin/bash`: Permission denied","level":"error","time":"2020-03-30T09:07:45.000757281Z"}

Here is the relevant findings:
```
find /home/user/.local/share/containers/ -name bash -type f
/home/user/.local/share/containers/storage/overlay/xxx/diff/usr/bin/bash

ll -Z /home/user/.local/share/containers/storage/overlay/xxx/diff/usr/bin/bash
-rwxr-xr-x. 1 user user staff_u:object_r:data_home_t:s0 1203992 Dec  6 13:08 /home/user/.local/share/containers/storage/overlay/xxx/diff/usr/bin/bash

mount | grep /home
/home type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)

type=AVC msg=audit(03/30/2020 11:07:45.756:685) : avc:  denied  { transition } for  pid=190930 comm=3 path=/usr/bin/bash dev="fuse" ino=67181813 scontext=staff_u:staff_r:container_runtime_t:s0 tcontext=system_u:system_r:container_t:s0:c433,c907 tclass=process permissive=0

sesearch -A -s container_runtime_t -t container_t -p transition
allow container_runtime_domain container_domain:process { dyntransition transition };
```
I can't figure out why even if the rule is present it does not apply here...

It works again when i'm doing **semanage permissive -a container_runtime_t** but not the perfect solution.

Thank you again for your time :)

**Comment by rhatdan** [comment]
I would run in permissive mode and gather all of the AVC's and then attach them.  I will add these rules, that you have found.

**Comment by rhatdan** [comment]
@wrabcak PTAL.  A lot of these should go into selinux-policy.

I would say that we should allow staff_t and User_t access to all user namespace capabilities.

$ sesearch -A -s staff_t -c cap_userns
allow staff_t staff_t:cap_userns { setpcap sys_admin sys_chroot };

Currently they are very limited.

**Comment by rhatdan** [comment]
One issue is that your staff_t is logging in without being fully ranged.

Your process should be 
staff_u:staff_r:staff_t:s0-s0:c0.c1024

But I believe it is only

staff_u:staff_r:staff_t:s0

I think that is why you are getting the transition error.  We need container_runitme_t to be fully ranged.

**Comment by rhatdan** [comment]
This rule
allow staff_t container_runtime_t:process { noatsecure rlimitinh siginh };
Should not be necessary, I believe

**Comment by tt-why** [comment]
> One issue is that your staff_t is logging in without being fully ranged.
> 
> Your process should be
> staff_u:staff_r:staff_t:s0-s0:c0.c1024
> 
> But I believe it is only
> 
> staff_u:staff_r:staff_t:s0
> 
> I think that is why you are getting the transition error. We need container_runitme_t to be fully ranged.

You were right ! I forgot to specify the complete range when confining my user in my kickstart...

So now i've that setup :
```
ps fauxZ|grep podman
staff_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 root 46406 0.0  0.0 6132 908 pts/0 S+ 16:14   0:00              \_ grep --color=auto podman
staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 user 44947 0.0  0.1 63344 33472 ? S 16:13   0:00 podman

id -Z
staff_u:staff_r:staff_t:s0-s0:c0.c1023
```

I've rebooted to apply the range, restorecon my home folder and i did a **podman system reset**.
But the following simple command always fails **podman run -it alpine:latest sh** :
```
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob aad63a933944 done  
Copying config a187dde48c done  
Writing manifest to image destination
Storing signatures
{"msg":"exec container process `/bin/sh`: Permission denied","level":"error","time":"2020-03-30T14:13:45.000319123Z"}

avc:  denied  { transition } for  pid=45145 comm=3 path=/bin/busybox dev="fuse" ino=33557878 scontext=staff_u:staff_r:container_runtime_t:s0 tcontext=system_u:system_r:container_t:s0:c313,c821 tclass=process permissive=0
```

Any idea ?

**Comment by wrabcak** [comment]
> @wrabcak PTAL. A lot of these should go into selinux-policy.
> 
> I would say that we should allow staff_t and User_t access to all user namespace capabilities.
> 
> $ sesearch -A -s staff_t -c cap_userns
> allow staff_t staff_t:cap_userns { setpcap sys_admin sys_chroot };
> 
> Currently they are very limited.

We can allow it for all except sys_ptrace. For that boolean we have specific deny_ptrace boolean. 

FYI @zpytela

**Comment by rhatdan** [comment]
SO the problem is staff_t:s0-s0:c0.10123 is transitioning to container_runtime_t:s0 when you execute podman, I forgot why the range is dropped...


```
cat > p.sh << _EOF 
#!/bin/sh
id -Z
_eof
chmod +x p.sh
chcon -t container_runtime_exec_t p.sh
./p.sh
```

**Comment by tt-why** [comment]
> SO the problem is staff_t:s0-s0:c0.10123 is transitioning to container_runtime_t:s0 when you execute podman, I forgot why the range is dropped...
> 
> ```
> cat > p.sh << _EOF 
> #!/bin/sh
> id -Z
> _eof
> chmod +x p.sh
> chcon -t container_runtime_exec_t p.sh
> ./p.sh
> ```
I've tried your script but it didn't transition to another domain unless i did a semanage -a permissive staff_t ...

Here is the avc (when staff_t=permissive) :
```
type=AVC msg=audit(03/31/2020 11:00:03.786:426) : avc:  denied  { nosuid_transition } for  pid=89233 comm=bash scontext=staff_u:staff_r:staff_t:s0-s0:c0.c1023 tcontext=staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 tclass=process2 permissive=1
```
But i see that in normal podman use case that you have authorized that : https://github.com/containers/container-selinux/blob/f00d1f4ec867be2aeb51b3b32c12a5a9a8015201/container.te#L42

Here is is ps fauxZ of a successful podman run -it alpine:latest sh :
```
staff_u:staff_r:staff_t:s0-s0:c0.c1023 user 22915 0.0  0.0   7132  4072 pts/1    Ss   10:27   0:00  \_ /bin/bash
staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 user 53594 0.6  0.2 1051740 58568 pts/1 Sl+ 10:42   0:00      \_ podman run -it alpine:latest sh
staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 user 53613 0.0  0.0 4372 2716 pts/1 S 10:42   0:00          \_ /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-7041947e-a275-010d-8737-069223a5f763 tap0
staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 user 43784 0.0  0.1 63344 33404 ? S 10:38   0:00 podman
staff_u:staff_r:container_runtime_t:s0-s0:c0.c1023 user 53612 0.0  0.0 5040 2052 ? Ss 10:42   0:00 /usr/bin/fuse-overlayfs -o lowerdir=/home/user/.local/share/containers/storage/overlay/l/HV2BUSAOM5FKWFVRWZVWPAIRDC,upperdir=/home/user/.local/share/containers/storage/overlay/1018760c5eb4ef9c1f8c9701ce5b3f2cb6395189e173
staff_u:staff_r:container_runtime_t:s0 user 53616 0.0  0.0  80404  2156 ?        Ssl  10:42   0:00 /usr/bin/conmon --api-version 1 -s -c cd7774b3904e8666a922ccf5a8d27a46e5256b92a150ed81d52b8b369f1f8b57 -u cd7774b3904e8666a922ccf5a8d27a46e5256b92a150ed81d52b8b369f1f8b57 -r /usr/bin/crun -b /home/user/.local/share/conta
system_u:system_r:container_t:s0:c245,c675 user 53620 0.0  0.0 1644 944 pts/0    Ss+  10:42   0:00  \_ sh
```

I might be wrong but if it it is a drop range problem it seems (thank's to f option of ps) that conmon is the father of the sh command inside my container. But as we can see, it doesn't have any range applied to it :/

**Comment by rhatdan** [comment]
If you add the nosuid_transition to the container runtime, does it work?

**Comment by rhatdan** [comment]
Does your user have NoNewPrivs turned on?

grep No /proc/self/status 
NoNewPrivs:	0

**Comment by tt-why** [comment]
> If you add the nosuid_transition to the container runtime, does it work?

The following avc was when i was running your specified p.sh i don't think it's the problem because it doesn't occur when using podman.

> Does your user have NoNewPrivs turned on?
> 
> grep No /proc/self/status
> NoNewPrivs: 0

Here is mine :
```
grep No /proc/self/status
NoNewPrivs:	0
```

The avc when running ** podman run -it alpine:latest sh** is still here and is not in the staff_t domain because staff_t is in permissive mode currently.
```
type=AVC msg=audit(03/31/2020 17:09:11.728:878) : avc:  denied  { transition } for  pid=460003 comm=3 path=/bin/busybox dev="fuse" ino=33557878 scontext=staff_u:staff_r:container_runtime_t:s0 tcontext=system_u:system_r:container_t:s0:c461,c919 tclass=process permissive=0
```

**Comment by rhatdan** [comment]
I believe this works now.

**Comment by laolux** [comment]
@rhatdan sorry if I just don't understand the solution, but I cannot run containers as staff_u

Whenever I try to run a container, I get `ype=AVC msg=audit(1623763861.316:852): avc:  denied  { transition } for  pid=3641 comm="3" path="/usr/bin/bash" dev="overlay" ino=4582721 scontext=staff_u:staff_r:container_runtime_t:s0 tcontext=system_u:system_r:container_t:s0:c363,c421 tclass=process permissive=0`

My teststaff user is SELinux user staff_u and has MLS/MCS Range s0-s0:c0.c1023

My OS is Fedora 34, podman is 3.2.1 and container-selinux version is 2.163.0

`semanage permissive -d container_runtime_t` permits me to run containers and I only get the avc denial I listed above, albeit with permissive=1.

What am I doing wrong?
