### ISSUE TITLE
Support `/usr/local` for all binaries?

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/container-selinux#99]
https://github.com/containers/container-selinux/blob/988431700370bf7f554ab6507c836a9aa19e47ff/container.fc

Currently, only `podman`, `runc`, `crun`, and `crio` are supported for `/usr/local` installation.

I'd expect `/usr/local` installation to be supported for all binaries.

Ref: https://github.com/containerd/containerd/pull/4346

**Comment by AkihiroSuda** [comment]
Also, `/usr/local/sbin/runc` is unsupported while `/usr/sbin/runc` and `/usr/local/bin/runc` are supported.

**Comment by dweomer** [comment]
Should be addressed by #98 which is still WIP as I am having trouble getting containerd 1.4 beta to pass all tests in `critest` with selinux enforcing on centos7 and suspect a policy miss.

**Comment by AkihiroSuda** [comment]
@rhatdan Please reopen, /usr/local/bin/docker isnt supported yet

**Comment by rhatdan** [comment]
Let's do this in a separate PR,
